module.exports = [
{id: 1, name: "Alcohol"},
{id: 2, name: "Cordial"},
{id: 3, name: "Rum"},
{id: 4, name: "Tequila"},
{id: 5, name: "Vermouth"},
{id: 6, name: "Vodka"},
{id: 7, name: "Whiskey"},
{id: 8, name: "Gin"},
{id: 9, name: "Brandy"},
{id: 10, name: "Acai"},
{id: 11, name: "Almond"},
{id: 12, name: "Amaretto"},
{id: 13, name: "Amaro"},
{id: 14, name: "Anejo"},
{id: 15, name: "Anise"},
{id: 16, name: "Anisette"},
{id: 17, name: "Apple"},
{id: 18, name: "Apricot"},
{id: 19, name: "Banana"},
{id: 20, name: "Berry"},
{id: 21, name: "Blanco"},
{id: 22, name: "Blueberry"},
{id: 23, name: "Bourbon"},
{id: 24, name: "Bourboun"},
{id: 25, name: "Butterscotch"},
{id: 26, name: "Canada Whisky"},
{id: 27, name: "Caramel"},
{id: 28, name: "Cherry"},
{id: 29, name: "Chocolate"},
{id: 30, name: "Cilantro"},
{id: 31, name: "Cinnamon"},
{id: 32, name: "Coconut"},
{id: 33, name: "Coffee"},
{id: 34, name: "Cognac"},
{id: 35, name: "Cranberry"},
{id: 36, name: "Dark Rum"},
{id: 37, name: "Domestic Whiskey"},
{id: 38, name: "Dry Vermouth"},
{id: 39, name: "Elderflower"},
{id: 40, name: "Espresso"},
{id: 41, name: "Flavored"},
{id: 42, name: "Gingerbread"},
{id: 43, name: "Gold Rum"},
{id: 44, name: "Grape"},
{id: 45, name: "Grapefruit"},
{id: 46, name: "Hazelnut"},
{id: 47, name: "Honehy"},
{id: 48, name: "Honey"},
{id: 49, name: "Irish"},
{id: 50, name: "Lemon"},
{id: 51, name: "Lime"},
{id: 52, name: "Mango"},
{id: 53, name: "Marshmello"},
{id: 54, name: "Melon"},
{id: 55, name: "Mint"},
{id: 56, name: "Orange"},
{id: 57, name: "Passion Fruit"},
{id: 58, name: "Peach"},
{id: 59, name: "Pear"},
{id: 60, name: "Peppermint"},
{id: 61, name: "Pineapple"},
{id: 62, name: "Pomagranite"},
{id: 63, name: "Pomegranate"},
{id: 64, name: "Raspberry"},
{id: 65, name: "Reposado"},
{id: 66, name: "Rye"},
{id: 67, name: "Scotch"},
{id: 68, name: "Sloe"},
{id: 69, name: "Sour"},
{id: 70, name: "Spiced Rum"},
{id: 71, name: "Sweet Vermouth"},
{id: 72, name: "Tennessee Whiskey"},
{id: 73, name: "Triple Sec"},
{id: 74, name: "Vanilla"},
{id: 75, name: "VS"},
{id: 76, name: "VSOP"},
{id: 77, name: "Watermelon"},
{id: 78, name: "White Rum"},
{id: 79, name: "White Whiskey"},
{id: 80, name: "XO"}
]
